In [167]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import numpy as np

In [168]:
url = "https://www.brotherswestand.com/pages/the-best-of-ethical-menswear"

In [169]:
html = requests.get(url)
soup = BeautifulSoup(html.content, "html.parser")

In [170]:
brands_ = soup.find_all("h4", {"class":"u-textUpper"})

In [171]:
brands = [i.getText() for i in brands_]
brands

['Brava Fabrics',
 'Elvis & Kresse',
 'Idioma',
 "Jollie's",
 'The Level Collective',
 'Knowledge Cotton Apparel',
 'Mud Jeans',
 'NWHR',
 'Riz',
 'Silverstick',
 'World Supporting Goods',
 'Yarmouth Oilskins']

In [172]:
description_ = soup.find_all("div", {"class":"page-content"})

In [173]:
description = [i.getText().strip() for i in description_]
description

['Characterful menswear crafted fairly in Portugal with organic and recycled fabrics by Barcelona based brand.',
 'Famous environmental designers making wallets and more from upcycled fire hose and other sustainable materials.',
 'Family run business with a global fan base.  Designer Seth Banks and  linguist Halle Banks champion World culture with unique prints on organic fabrics.',
 "Fresh organic and recycled socks with a 'wear a pair, share a pair' business model.",
 'Cornwall based brand celebrating balanced living with nature inspired prints and sustainable production.',
 'Experienced Danish brand making smart low impact clothing for those who love nature.',
 'Dutch circular economy brand using exlusively organic and recycled fibres and producing in one ethical factory in Tunisia.',
 'Streetwear has been slow to incorperate sustainable practices. New kid on the block, Spanish brand NWHR are stepping up to lead the way.',
 'Independent British swimwear brand crafting stunning sustainable shorts from recycled and recylcable fabrics.',
 'British brand making quality organic essentials and adventure-wear at a fair price.',
 'Environmental streetwear brand highlighting social issues with stand out designs and ethical production.',
 'British brand crafting quality workwear in their own factory for over one hundred years.']

In [174]:
links_ = soup.find_all("div", {"class":"o-grid o-grid--item"})

In [175]:
links = [i.find('a').get('href') for i in links_]
links

['/collections/brava-fabrics',
 '/collections/elvis-kresse',
 '/collections/idioma',
 '/collections/jollies',
 '/collections/level-collective',
 '/collections/knowledge-cotton-apparel',
 '/collections/mud-jeans',
 '/collections/nwhr',
 '/collections/riz',
 '/collections/silverstick',
 '/collections/world-supporting-goods-by-lars-godeke',
 '/collections/yarmouth-oilskins']

In [176]:
def retailer_scraping (url):
    html = requests.get(url)
    soup = BeautifulSoup(html.content, "html.parser")
    
    brands_ = soup.find_all("h4", {"class":"u-textUpper"})
    brands = [i.getText() for i in brands_]
    
    description_ = soup.find_all("div", {"class":"page-content"})
    description = [i.getText().strip() for i in description_]

    links_ = soup.find_all("div", {"class":"o-grid o-grid--item"})
    links = [i.find('a').get('href') for i in links_]

    retailer_brands = {
        'Brands': brands,
        'Description': description,
        'Links': links
    }
    
    return pd.DataFrame(retailer_brands)

In [180]:
retailer = retailer_scraping('https://www.brotherswestand.com/pages/the-best-of-ethical-menswear')
retailer

,Brands,Description,Links
0,Brava Fabrics,Characterful menswear crafted fairly in Portug...,/collections/brava-fabrics
1,Elvis & Kresse,Famous environmental designers making wallets ...,/collections/elvis-kresse
2,Idioma,Family run business with a global fan base. D...,/collections/idioma
3,Jollie's,Fresh organic and recycled socks with a 'wear ...,/collections/jollies
4,The Level Collective,Cornwall based brand celebrating balanced livi...,/collections/level-collective
5,Knowledge Cotton Apparel,Experienced Danish brand making smart low impa...,/collections/knowledge-cotton-apparel
6,Mud Jeans,Dutch circular economy brand using exlusively ...,/collections/mud-jeans
7,NWHR,Streetwear has been slow to incorperate sustai...,/collections/nwhr
8,Riz,Independent British swimwear brand crafting st...,/collections/riz
9,Silverstick,British brand making quality organic essential...,/collections/silverstick
10,World Supporting Goods,Environmental streetwear brand highlighting so...,/collections/world-supporting-goods-by-lars-go...
11,Yarmouth Oilskins,British brand crafting quality workwear in the...,/collections/yarmouth-oilskins

In [181]:
# inside the brand, get all products + prices
# get location of the brand

# test function, based on how it works with a single brand

In [182]:
def single_brand (url):
    html = requests.get(url)
    soup = BeautifulSoup(html.content, "html.parser")

    product_ = soup.find_all("p", {"class": "block__p"})
    product = [i.getText().strip() for i in product_]

    price_s = soup.find_all("strong", {"class": "price-item price-item--sale"})
    price_sale = [i.getText().replace('£', '').strip() for i in price_s]
    
    brand_ = soup.find_all("h4", {"class": "block__title block__title--small"})
    brand = [i.getText() for i in brand_]

    brand_products = {
        'Product': product,
        'Selling price': price_sale,
        'Brand': brand
    }
    
    return pd.DataFrame(brand_products)

In [183]:
df = single_brand ('https://www.brotherswestand.com/collections/brava-fabrics')
df

                              Product Selling price          Brand
0                Oversize Pants Storm        114.00  Brava Fabrics
1   Brava Passerine Aloha Shirt Coiro         88.00  Brava Fabrics
2                      Chilli T-Shirt         40.00  Brava Fabrics
3           Brava Tiger T-Shirt Storm         44.00  Brava Fabrics
4          Brava Heart T-Shirt Morera         44.00  Brava Fabrics
5          Brava Iceberg T-Shirt Blue         40.00  Brava Fabrics
6       Brava Patch Playmobil T-Shirt         44.00  Brava Fabrics
7                   Corduroy Trousers        114.00  Brava Fabrics
8                      Chilli T-Shirt         40.00  Brava Fabrics
9                       Comfort Chino        114.00  Brava Fabrics
10                      Comfort Chino        114.00  Brava Fabrics
11                     Ripstop Jacket        105.00  Brava Fabrics
12            Nuuk Regular Shirt Blue         66.00  Brava Fabrics
13                    Bosco Overshirt        114.00  Brava Fabrics
14             Stripes Overshirt Navy        105.00  Brava Fabrics
15                Lined Bomber Jacket        165.00  Brava Fabrics
16                Lined Bomber Jacket        129.00  Brava Fabrics
17                 Workwear Pants Mud        114.00  Brava Fabrics
18     Corduroy Overshirt Stone Green        114.00  Brava Fabrics
19                  Corduroy Trousers        114.00  Brava Fabrics
20        Stripes Jumper - Dark Green        114.00  Brava Fabrics
21              Stripes Jumper - Navy         65.00  Brava Fabrics
22                      Comfort Chino        105.00  Brava Fabrics
23            Ripstop Oversize Shorts         80.00  Brava Fabrics
24            Ripstop Oversize Shorts         80.00  Brava Fabrics
25            Ripstop Oversize Shorts         80.00  Brava Fabrics
26                     Gelato T-Shirt         40.00  Brava Fabrics
27                      Stripes Shirt         88.00  Brava Fabrics
28             Euroflax Linen Shacket         97.00  Brava Fabrics
29                     Ripstop Jacket        105.00  Brava Fabrics
30                      Oversize Pant        105.00  Brava Fabrics
31                      Oversize Pant        105.00  Brava Fabrics
32                      Oversize Pant        105.00  Brava Fabrics
33            Ocean Seersucker Shorts         80.00  Brava Fabrics
34                 Sunbathing T-Shirt         40.00  Brava Fabrics
35      Waterfront Wine Merino Jumper        131.00  Brava Fabrics
36      EcoVero™ Narciso Stripe Shirt         49.00  Brava Fabrics
37         Inka Gold Oversized Shorts         80.00  Brava Fabrics
38              Navy Oversized Shorts         80.00  Brava Fabrics
39     Seersucker Ocean Casual Chinos        105.00  Brava Fabrics
40     Euroflax Linen Inka Gold Pants        105.00  Brava Fabrics
41                 Capetonian T-shirt         40.00  Brava Fabrics
42                    Ndebele T-shirt         40.00  Brava Fabrics
43                     Pleated Chinos         80.00  Brava Fabrics
44                     Pleated Chinos         80.00  Brava Fabrics
45   Waterfront Mustard Merino Jumper        131.00  Brava Fabrics

In [193]:
def all_brands (column_retailer):
    
    column_retailer = column_retailer.apply(lambda x: f"https://www.brotherswestand.com{x}")
        
    all_products = pd.DataFrame()
    
    for i in column_retailer:
        df = single_brand(i)
        
        all_products = pd.concat([all_products, df], ignore_index=True)
            
    return pd.DataFrame(all_products)

In [194]:
retailers = all_brands (retailer_scraping(url).Links)
retailers

                               Product Selling price              Brand
0                 Oversize Pants Storm        114.00      Brava Fabrics
1    Brava Passerine Aloha Shirt Coiro         88.00      Brava Fabrics
2                       Chilli T-Shirt         40.00      Brava Fabrics
3            Brava Tiger T-Shirt Storm         44.00      Brava Fabrics
4           Brava Heart T-Shirt Morera         44.00      Brava Fabrics
..                                 ...           ...                ...
294                     Drivers Jacket        160.00  Yarmouth Oilskins
295                     Drivers Jacket        160.00  Yarmouth Oilskins
296                       Hooded Smock        300.00  Yarmouth Oilskins
297                       Hooded Smock        300.00  Yarmouth Oilskins
298                       Hooded Smock        300.00  Yarmouth Oilskins

[299 rows x 3 columns]

In [48]:
# convert Selling price from string -> float -> integer

retailers['Selling price'] = retailers['Selling price'].apply(lambda x: int(float(x)))
retailers

                               Product  Selling price              Brand
0                 Oversize Pants Storm            114      Brava Fabrics
1    Brava Passerine Aloha Shirt Coiro             88      Brava Fabrics
2                       Chilli T-Shirt             40      Brava Fabrics
3            Brava Tiger T-Shirt Storm             44      Brava Fabrics
4           Brava Heart T-Shirt Morera             44      Brava Fabrics
..                                 ...            ...                ...
294                     Drivers Jacket            160  Yarmouth Oilskins
295                     Drivers Jacket            160  Yarmouth Oilskins
296                       Hooded Smock            300  Yarmouth Oilskins
297                       Hooded Smock            300  Yarmouth Oilskins
298                       Hooded Smock            300  Yarmouth Oilskins

[299 rows x 3 columns]

In [49]:
retailers['Selling price'].unique()

array([114,  88,  40,  44, 105,  66, 165, 129,  65,  80,  97, 131,  49,
        41,  78,  35, 102,  73,  58, 310, 260,  39,  45,  37,  79,  84,
        94,  12,  95, 120,  25, 119, 138,  90, 125, 109, 126, 104, 130,
        50,  70,  60,  32, 115, 100,  55,  28,  24,  26,  30,  22,  52,
       160, 200, 150, 195, 300])

In [106]:
retailers['Price-point'] = retailers['Selling price'].apply(lambda x: 'low-end' if x <= 40 else ('mid-end' if 41 < x < 99 else 'high-end'))
retailers

,Product,Selling price,Brand,Price-point
0,Oversize Pants Storm,114,Brava Fabrics,high-end
1,Brava Passerine Aloha Shirt Coiro,88,Brava Fabrics,mid-end
2,Chilli T-Shirt,40,Brava Fabrics,low-end
3,Brava Tiger T-Shirt Storm,44,Brava Fabrics,mid-end
4,Brava Heart T-Shirt Morera,44,Brava Fabrics,mid-end
...,...,...,...,...
294,Drivers Jacket,160,Yarmouth Oilskins,high-end
295,Drivers Jacket,160,Yarmouth Oilskins,high-end
296,Hooded Smock,300,Yarmouth Oilskins,high-end
297,Hooded Smock,300,Yarmouth Oilskins,high-end
298,Hooded Smock,300,Yarmouth Oilskins,high-end

In [107]:
retailers['Price-point'].value_counts()

mid-end     118
high-end    109
low-end      72
Name: Price-point, dtype: int64

In [108]:
retailers['Selling price'].groupby(retailers.Brand).describe()

,count,mean,std,min,25%,50%,75%,max
Brand,,,,,,,,
Brava Fabrics,46.0,87.652174,31.640493,40.0,65.25,92.5,114.0,165.0
Elvis and Kresse,19.0,121.842105,99.210362,35.0,66.00,73.0,181.0,310.0
Idioma,23.0,53.086957,19.516690,35.0,38.00,45.0,64.0,94.0
Jollie's,1.0,12.000000,NaN,12.0,12.00,12.0,12.0,12.0
Knowledge Cotton Apparel,48.0,68.541667,35.595217,25.0,32.50,80.0,95.0,138.0
Level Collective,20.0,41.000000,12.311740,35.0,35.00,35.0,35.0,65.0
Mud Jeans,35.0,105.142857,13.056760,80.0,104.00,109.0,109.0,130.0
NWHR,19.0,46.789474,9.852123,32.0,41.00,41.0,54.0,70.0
Riz,7.0,107.857143,9.063270,95.0,100.00,115.0,115.0,115.0
Silverstick,48.0,44.583333,15.605282,22.0,28.00,50.0,55.0,65.0
World Supporting Goods by Lars Gödeke,6.0,50.166667,4.490731,41.0,52.00,52.0,52.0,52.0
Yarmouth Oilskins,27.0,163.888889,55.890231,95.0,140.00,160.0,160.0,300.0

In [109]:
retailers['Selling price'].groupby(retailers['Price-point']).describe()

             count        mean        std   min     25%    50%    75%    max
Price-point
high-end     109.0  125.155963  56.994992  41.0  105.00  114.0  131.0  310.0
low-end       72.0   31.750000   6.222970  12.0   25.00   35.0   37.0   40.0
mid-end      118.0   67.389831  15.916467  44.0   52.75   65.0   80.0   97.0

In [215]:
def brand_analysis (df):
    
    retailers = all_brands (retailer_scraping(url).Links)
    
    retailers['Selling price'] = retailers['Selling price'].apply(lambda x: int(float(x)))

    retailers['Price-point'] = retailers['Selling price'].apply(lambda x: 'low-end' if x <= 40 
                                                                else ('mid-end' if 41 < x < 99 else 'high-end'))
    
    return retailers['Selling price'].groupby(retailers.Brand).describe()

In [216]:
brand_analysis (all_brands)

,count,mean,std,min,25%,50%,75%,max
Brand,,,,,,,,
Brava Fabrics,46.0,87.652174,31.640493,40.0,65.25,92.5,114.0,165.0
Elvis and Kresse,19.0,121.842105,99.210362,35.0,66.00,73.0,181.0,310.0
Idioma,23.0,53.086957,19.516690,35.0,38.00,45.0,64.0,94.0
Jollie's,1.0,12.000000,NaN,12.0,12.00,12.0,12.0,12.0
Knowledge Cotton Apparel,48.0,70.833333,35.794528,25.0,32.50,80.0,95.0,138.0
Level Collective,20.0,41.000000,12.311740,35.0,35.00,35.0,35.0,65.0
Mud Jeans,35.0,105.142857,13.056760,80.0,104.00,109.0,109.0,130.0
NWHR,19.0,46.789474,9.852123,32.0,41.00,41.0,54.0,70.0
Riz,7.0,107.857143,9.063270,95.0,100.00,115.0,115.0,115.0
Silverstick,48.0,44.583333,15.605282,22.0,28.00,50.0,55.0,65.0
World Supporting Goods by Lars Gödeke,6.0,50.166667,4.490731,41.0,52.00,52.0,52.0,52.0
Yarmouth Oilskins,27.0,163.888889,55.890231,95.0,140.00,160.0,160.0,300.0

In [227]:
def price_point_brands (df):
    result = brand_analysis (all_brands)
    
    result['Price-point'] = result['75%'].apply(lambda x: 'low-end' if x <= 40 
                                                 else ('mid-end' if 41 < x < 99 else 'high-end'))
    
    return result

In [228]:
price_point_brands (brand_analysis)

,count,mean,std,min,25%,50%,75%,max,Price-point
Brand,,,,,,,,,
Brava Fabrics,46.0,87.652174,31.640493,40.0,65.25,92.5,114.0,165.0,high-end
Elvis and Kresse,19.0,121.842105,99.210362,35.0,66.00,73.0,181.0,310.0,high-end
Idioma,23.0,53.086957,19.516690,35.0,38.00,45.0,64.0,94.0,mid-end
Jollie's,1.0,12.000000,NaN,12.0,12.00,12.0,12.0,12.0,low-end
Knowledge Cotton Apparel,48.0,70.833333,35.794528,25.0,32.50,80.0,95.0,138.0,mid-end
Level Collective,20.0,41.000000,12.311740,35.0,35.00,35.0,35.0,65.0,low-end
Mud Jeans,35.0,105.142857,13.056760,80.0,104.00,109.0,109.0,130.0,high-end
NWHR,19.0,46.789474,9.852123,32.0,41.00,41.0,54.0,70.0,mid-end
Riz,7.0,107.857143,9.063270,95.0,100.00,115.0,115.0,115.0,high-end
Silverstick,48.0,44.583333,15.605282,22.0,28.00,50.0,55.0,65.0,mid-end
World Supporting Goods by Lars Gödeke,6.0,50.166667,4.490731,41.0,52.00,52.0,52.0,52.0,mid-end
Yarmouth Oilskins,27.0,163.888889,55.890231,95.0,140.00,160.0,160.0,300.0,high-end

In [218]:
def price_point_analysis (df):
    retailers = all_brands (retailer_scraping(url).Links)
    
    retailers['Selling price'] = retailers['Selling price'].apply(lambda x: int(float(x)))

    retailers['Price-point'] = retailers['Selling price'].apply(lambda x: 'low-end' if x <= 40 
                                                                else ('mid-end' if 41 < x < 99 else 'high-end'))
    
    return retailers['Selling price'].groupby(retailers['Price-point']).describe()

In [219]:
price_point_analysis (all_brands)

             count        mean        std   min    25%    50%    75%    max
Price-point
high-end     110.0  124.972727  56.765486  41.0  105.0  111.5  131.0  310.0
low-end       72.0   31.750000   6.222970  12.0   25.0   35.0   37.0   40.0
mid-end      117.0   68.008547  15.907868  44.0   55.0   65.0   80.0   97.0

In [ ]:
# WHAT IS THE OBJECTIVE ?
# Market research: retailer analysis. Evaluate potential retail partners, based on:
    # brands in their portfolio
    # nr. of products per brand
    # price-point per brand
    # use this data to further investigate 

# create a new column where you define if a price of each product is low, mid, or high-end price range 
# (consider assigning an integer 1-3 instead)
# group by brand:
    # count of products per brand
    # on average, is the brand low, mid or high-end

# insert all your functions into a src.py file (jupyter -> new -> .txt)
# create a new notebook, where you call the source code (import src.py)

# readme